name: PR Logger
on: [push]

jobs:
  build:
    name: Getting current PR log
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from the log repository
        uses: actions/checkout@v2
        with:
          repository: snic104/actions-destination
          token: ${{ secrets.SNIC104_TOKEN }}
      - name: List
        run: ls
